[[main]]
  name = "Home"
  url = ""
  weight = -120
[[main]]
  name = "Gallery"
  url = "gallery"
  weight = -108
[[main]]
  name = "Achievements"
  identifier = "Achievements"
  url = ""
  weight = -109
[[main]]
  parent = "Achievements"
  name = "Prize"
  url = "prize"
  weight = -112 
[[main]]
  parent = "Achievements"
  name = "In News"
  url = "news"
  weight = -111  
[[main]]
  parent = "Achievements"
  name = "Certificate"
  url = "certificate"
  weight = -112  
[[main]]
  parent = "Achievements"
  name = "Event"
  url = "event"
  weight = -113  


# Submenus are done this way: parent -> identifier

[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/pranav083"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/pranav083"
[[main]]
  parent = "Links"
  name = "Resume"
  url = "https://drive.google.com/file/d/1Z61ZhJWqCK8pFAiZJzSlyzumnD83A6BH/view"
[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/pranav083"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/pranav083"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/pranav083"
[[social]]
  name = "youtube"
  weight = 4
  url = "https://www.youtube.com/channel/UCvs9yPyIP98w-6CKLNw_eEw"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
