[[main]]
  name = "Home"
  url = ""
  weight = -110
[[main]]
  name = "Gallery"
  url = "2020/update"
  weight = -108
[[main]]
  name = "Archives"
  identifier = "Archives"
  weight = -109
[[main]]
  parent = "Archives"
  name = "2020"
  url = "2020/markdown-syntax"
  weight = -112 
[[main]]
  parent = "Archives"
  name = "2021"
  url = "post/lvgl_esp32_setup"
  weight = -111  
# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/pranav083"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/pranav083"
[[main]]
  parent = "Links"
  name = "Resume"
  url = "https://drive.google.com/file/d/1Z61ZhJWqCK8pFAiZJzSlyzumnD83A6BH/view"
[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/pranav083"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/pranav083"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/pranav083"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
